export const STRINGS = {
  APP: {
    NAME: 'Clearday',
    TAGLINE: 'Your day, your way.',
    LOGO_EMOJI: '☀️',
  },

  LOGIN: {
    TITLE: 'Welcome back',
    SUBTITLE: 'Sign in to continue',
    EMAIL_LABEL: 'Email',
    EMAIL_PLACEHOLDER: 'you@example.com',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: '••••••••',
    BUTTON: 'Sign In',
    FOOTER_TEXT: "Don't have an account?",
    FOOTER_LINK: 'Sign up',
  },

  SIGNUP: {
    TITLE: 'Create account',
    SUBTITLE: 'Get started for free',
    NAME_LABEL: 'Full Name',
    NAME_PLACEHOLDER: 'Jane Doe',
    EMAIL_LABEL: 'Email',
    EMAIL_PLACEHOLDER: 'you@example.com',
    PASSWORD_LABEL: 'Password',
    PASSWORD_PLACEHOLDER: 'Min. 6 characters',
    CONFIRM_PASSWORD_LABEL: 'Confirm Password',
    CONFIRM_PASSWORD_PLACEHOLDER: 'Re-enter password',
    BUTTON: 'Create Account',
    FOOTER_TEXT: 'Already have an account?',
    FOOTER_LINK: 'Sign in',
  },

  HOME: {
    USER_FALLBACK: 'User',
    SECTION_DUE_TODAY: 'Due Today',
    SECTION_DUE_TOMORROW: 'Due Tomorrow',
    SECTION_OVERVIEW: "Today's overview",
    WELCOME_TITLE: "You're all set! ☀️",
    WELCOME_SUBTITLE:
      "There is nothing due today. Take a moment to relax or plan for tomorrow. You've got this! 💪",
    SECTION_UPCOMING: 'Upcoming',
    A11Y_OPEN_PROFILE: 'Open profile',
    SECTION_REMINDERS_TODAY: "Today's Reminders",
    SECTION_WEATHER_ALERTS: '🌤 Weather at Task Time',
    WEATHER_ALERT_RESCHEDULE: 'Reschedule?',
    weatherAlertBody: (desc: string, time: string): string =>
      `${desc} expected at ${time}`,
    a11yOpenSection: (label: string): string => `Open ${label}`,
    a11yDismissAlert: (title: string): string => `Dismiss weather alert for ${title}`,
  },

  PROFILE: {
    TITLE: 'Profile',
    BACK: '← Back',
    SECTION_SETTINGS: 'Settings',
    THEME_DARK: '🌙 Dark Theme',
    THEME_LIGHT: '☀️ Light Theme',
    USER_NAME_FALLBACK: 'User',
    USER_EMAIL_FALLBACK: 'user@example.com',
    SIGN_OUT: 'Sign Out',
    A11Y_GO_BACK: 'Go back',
  },

  TASK: {
    TITLE: 'Tasks',
    BACK_ICON: '←',
    SEARCH_PLACEHOLDER: 'Search tasks…',
    ADD_PLACEHOLDER: 'New task…',
    ADD_BUTTON: 'Add Task',
    ICON_CAMERA: '📷',
    ICON_GALLERY: '🖼️',
    ICON_DATE: '📅',
    ICON_TIME: '🕐',
    ICON_SEARCH: '🔍',
    ICON_REMOVE: '✕',
    ICON_CHECKMARK: '✓',
    A11Y_GO_BACK: 'Go back',
    A11Y_SEARCH_CLEAR: 'Clear search',
    A11Y_SEARCH: 'Search tasks',
    A11Y_NEW_TASK: 'New task title',
    A11Y_TAKE_PHOTO: 'Take photo',
    A11Y_GALLERY: 'Choose from gallery',
    A11Y_DATE_PICKER: 'Pick due date',
    A11Y_TIME_PICKER: 'Pick due time',
    A11Y_REMOVE_DATE: 'Remove due date',
    A11Y_REMOVE_TIME: 'Remove due time',
    A11Y_REMOVE_IMAGE: 'Remove image',
    A11Y_ADD_TASK: 'Add task',
    EMPTY_SEARCH_TITLE: 'No results found',
    EMPTY_SEARCH_EMOJI: '🔍',
    EMPTY_COMPLETED_TITLE: 'Nothing completed yet',
    EMPTY_COMPLETED_EMOJI: '🎉',
    EMPTY_DEFAULT_TITLE: 'No tasks yet',
    EMPTY_DEFAULT_EMOJI: '📋',
    EMPTY_COMPLETED_SUBTITLE: 'Complete a task and it will show up here.',
    EMPTY_DEFAULT_SUBTITLE: 'Add your first task above to get started.',
    CAMERA_UNAVAILABLE_TITLE: 'Camera unavailable',
    CAMERA_UNAVAILABLE_MSG: 'Camera is not accessible on this device. Would you like to choose a photo from your library instead?',
    CAMERA_UNAVAILABLE_GALLERY_BTN: 'Open Gallery',
    CAMERA_UNAVAILABLE_CANCEL_BTN: 'Cancel',
    CAMERA_PERMISSION_TITLE: 'Camera access required',
    CAMERA_PERMISSION_MSG: 'Please enable camera access in Settings to take photos.',
    emptySearchSubtitle: (q: string): string => `No tasks matching "${q}"`,
    subtitle: (active: number, done: number): string => `${active} active · ${done} done`,
    a11yDeleteTask: (title: string): string => `Delete ${title}`,
  },

  NOTE: {
    TITLE: 'Notes',
    BACK_ICON: '←',
    A11Y_GO_BACK: 'Go back',
    ICON_SEARCH: '🔍',
    ICON_REMOVE: '✕',
    ICON_ADD: '+',
    SEARCH_PLACEHOLDER: 'Search notes…',
    ADD_TITLE_PLACEHOLDER: 'Note title…',
    ADD_BODY_PLACEHOLDER: 'Write something…',
    ADD_BUTTON: 'Save Note',
    EDIT_BUTTON: 'Save Changes',
    CANCEL_BUTTON: 'Cancel',
    EMPTY_EMOJI: '📝',
    EMPTY_TITLE: 'No notes yet',
    EMPTY_SUBTITLE: 'Tap + to write your first note.',
    EMPTY_SEARCH_EMOJI: '🔍',
    EMPTY_SEARCH_TITLE: 'No results found',
    A11Y_SEARCH: 'Search notes',
    A11Y_SEARCH_CLEAR: 'Clear search',
    A11Y_ADD_NOTE: 'Add note',
    A11Y_OPEN_COMPOSE: 'New note',
    emptySearchSubtitle: (q: string): string => `No notes matching "${q}"`,
    subtitle: (count: number): string => `${count} note${count === 1 ? '' : 's'}`,
    a11yDeleteNote: (title: string): string => `Delete ${title}`,
    a11yEditNote: (title: string): string => `Edit ${title}`,
  },

  REMINDER: {
    TITLE: 'Reminders',
    BACK_ICON: '←',
    A11Y_GO_BACK: 'Go back',
    ICON_SEARCH: '🔍',
    ICON_REMOVE: '✕',
    ICON_ADD: '+',
    ICON_BELL: '🔔',
    ICON_CHECKMARK: '✓',
    SEARCH_PLACEHOLDER: 'Search reminders…',
    COMPOSE_HEADING_ADD: 'New Reminder',
    COMPOSE_HEADING_EDIT: 'Edit Reminder',
    ADD_TITLE_PLACEHOLDER: 'Remind me to…',
    DATE_LABEL: 'Date',
    TIME_LABEL: 'Time',
    ADD_BUTTON: 'Set Reminder',
    CANCEL_BUTTON: 'Cancel',
    PERMISSION_DENIED_TITLE: 'Notifications disabled',
    PERMISSION_DENIED_MSG: 'Enable notifications in Settings to receive reminder alerts.',
    EMPTY_EMOJI: '🔔',
    EMPTY_TITLE: 'No reminders yet',
    EMPTY_SUBTITLE: 'Tap + to set your first reminder.',
    EMPTY_SEARCH_EMOJI: '🔍',
    EMPTY_SEARCH_TITLE: 'No results found',
    SECTION_UPCOMING: 'Upcoming',
    SECTION_PAST: 'Past',
    A11Y_SEARCH: 'Search reminders',
    A11Y_SEARCH_CLEAR: 'Clear search',
    A11Y_ADD_REMINDER: 'Set reminder',
    A11Y_OPEN_COMPOSE: 'New reminder',
    A11Y_TOGGLE: 'Mark reminder complete',
    emptySearchSubtitle: (q: string): string => `No reminders matching "${q}"`,
    subtitle: (count: number): string => `${count} reminder${count === 1 ? '' : 's'}`,
    a11yDeleteReminder: (title: string): string => `Delete ${title}`,
    formatDateTime: (ts: number): string => {
      const d = new Date(ts);
      return d.toLocaleString(undefined, {
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    },
  },

  WEATHER: {
    LOADING: 'Fetching weather…',
    ERROR: 'Weather unavailable',
    LOCATION_DENIED: 'Location access denied',
    LOCATION_DENIED_MSG: 'Enable location access in Settings to see the current weather.',
    FEELS_LIKE: (temp: number): string => `Feels like ${temp}°`,
    HUMIDITY: (pct: number): string => `💧 ${pct}%`,
    WIND: (mps: number): string => `💨 ${mps} m/s`,
  },

  INPUT: {
    SHOW_PASSWORD: 'Show',
    HIDE_PASSWORD: 'Hide',
    A11Y_SHOW_PASSWORD: 'Show password',
    A11Y_HIDE_PASSWORD: 'Hide password',
  },
};
